version: '3.8'

services:
  api:
    build: .
    container_name: royal_shield_backend_express
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
